### ISSUE TITLE
erster Durchschuß

### ISSUE THREAD

**Issue by airballking** [SemRoCo/giskardpy#1]
- [x] set up package (Simon)
- [ ] QPProblemBuilder (Adrian)
- [x] integrate qpOases (Simon ?)
- [ ] test case: point robot with 3d goal (Adrian)

@aroefer & @ichumuh is this fine for you?

**Comment by ichumuh** [comment]
Yes

**Comment by airballking** [comment]
I took the liberty of sketching the toy problem with specific numbers on my whiteboard. For future references, this is it:

![giskardpy_toy_problem](https://user-images.githubusercontent.com/1560050/31485455-2dd4dd3a-af34-11e7-97ac-b6d172cbdee3.jpg)

Edit: I spotted a mistake in l_A: It should be (-1.3 - 1.05) instead of (1.3 - 1.05) for the second entry. Sorry about that.
