### ISSUE TITLE
Documentation/Tutorials

### ISSUE THREAD

**Issue by ARoefer** [SemRoCo/giskardpy#12]
Hi Guys,

I'm trying to get into the v0.2 and it's very difficult because of the lack of documentation.
I think a small tutorial explaining how controller, god map and inputs are supposed to be used is really needed.

**Comment by airballking** [comment]
Agreed. Indeed, we have already formulated this as an internal goal with deadline end of September.

**Comment by ARoefer** [comment]
@ichumuh Thank you for the update! I'll look through the changes when I can find the time. I'm looking forward to the tutorials. The idea of the universes looks very intriguing!
