### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by NeumannM89** [SemRoCo/giskardpy#15]
I get "Cannot locate rosdep definition for [ros_kinetic_urdfdom_py]" during the install.

**Comment by ichumuh** [comment]
try to install it manually
sudo apt-get install ros-kinetic-urdfdom-py

**Comment by airballking** [comment]
I think adding ```urdfdom_py``` and the likes to the ```package.xml``` would be the better option. Then, the install instructions would automatically cause the installation.

**Comment by ichumuh** [comment]
It is listed in package.xml, but rosdep didn't manage to install it.

**Comment by airballking** [comment]
Oh! I just checked, the dependency was incorrectly stated. I just fixed that on that master branch. I guess we can close the issue, right?

**Comment by ichumuh** [comment]
yes
