### ISSUE TITLE
Change SymengineController's interface

### ISSUE THREAD

**Issue by ARoefer** [SemRoCo/giskardpy#17]
Hi,

I've recently updated an old system of mine to work with the new v0.2 version. I noticed that the new SymEngineController can only be passed a URDF path, not a Robot instance. I think this interface should be changed to accept a complete robot, since there's information that can not be encoded in URDF, like a model for base navigation. 
Of course I can still inherit from the controller and override __init__ completely, but that's very unclean. To afford both use cases, the class could offer a static constructor which uses a URDF path, or the type of the given parameter could be analyzed in __init__.

**Comment by ichumuh** [comment]
I agree. On the hypothesis (the name of a cool python testing framework) branch, I'm currently writing tests, refactoring and writing documentation. On that branch SymengineController only accepts a Robot class in init, to remove the urdf dependency from that class. This branch will get merge into devel_v0.2 and master when I'm finished.

**Comment by ARoefer** [comment]
Alright, thank you for the update! Looking forward to the merge.
