### ISSUE TITLE
Runtime comparison 

### ISSUE THREAD

**Issue by ichumuh** [SemRoCo/giskardpy#5]
A small benchmark using a cartesian controller on pr2. (test/test_controller.py:TestController.test_cart_controller_pr2)
Run on machine with 4ghz and 16gb ram + line_profiler.

\ | pure sympy | sympy + numpy | sympy + cython | pure symengine 
--- | --- | --- | --- | --- 
init (eq statements + jacobian + autowrap) | 11.5s | 21s | 53s | 0.15s 
eq statements | 0.85s | 0.85s | 0.85s | <0.001s 
jacobian | 9.8s | 9.8s | 9.8s | 0.05s 
autowrap | - | 10.5s | 43s | - 
get_next_command | 108s | 0.01s | 0.00025s | 0.049s

**Comment by airballking** [comment]
@ichumuh Thanks for providing! Some quick questions:

(1) On what type of machine was that run?
(2) Could you describe (in one sentence) what 'eq statements', 'jacobian', and 'next_cmd (per hit)' mean? I feel unsure about some of them.

As a guideline, the controller should run at least 100Hz to be useful on the real robot. Faster is always better.

Also, this is running qpOases, right?

Finally, do think it makes sense to include Theano and Tensorflow into the comparison?

**Comment by ichumuh** [comment]
(1) I have added the machine speccs to the opening post, the overall test is about 25-50% faster without the profiler, but hard to tell if everything is equally effected. Sorry that I forgot to mention that earlier.
(2) 

- eq statements: CartesianController.make_constraints() + robot.add_chain_joints() (which creates the forward kinematic equations in sympy terms)
- jacobian: line 74 in qpbuilder
- next_cmd: controller.get_next_cmd() call, this consists of function evaluation and qp problem solving

(3) yes, and the runtime is negligible

(4) I would like to include them but it's hard for me to estimate how much time it will take.

**Comment by airballking** [comment]
@ichumuh thanks for the updates and infos. What is your next step on this?

**Comment by ichumuh** [comment]
I ran a few more tests -without- line profiler but on the same machine. This time I omitted pure sympy because it's too slow anyway. The next command was called 200 times.
1. For the first benchmark I used the pr2 joint state controller test as an example for a very simple controller:

\ | sympy + numpy | sympy + cython | symengine
---|---|---|---
init | 1.3 | 32 | 0.026
eq statements | 0.3 | 0.3 | 0.003
jacobian | 0.003 | 0.003 | 0.0000003
autowrap | 0.97 | 31.5 | -
get_next_command | 0.00028 | 0.00017 | 0.0055
get_next_cmd std | 0.000005 | 0.000005 | 0.0012

2. the cartesian controller from the opening post but, again, this time without the line profiler:

\ | sympy + numpy | sympy + cython | symengine
---|---|---|---
init | 7.8 | 38 | 0.125
eq statements | 0.32 | 0.32 | 0.013
jacobian | 3.2 | 3.2 | 0.046
autowrap | 4.2 | 31 | -
get_next_command | 0.0095 | 0.00013 | 0.048
get_next_cmd std | 0.0024 | 0.00004 | 0.0009

3. I have tried out a cartesian controller with the additional constraint that it tries to stay on a straight line between start and goal pose:

\ | sympy + numpy | sympy + cython | symengine
---|---|---|---
init | 13.4 | 44.2 | 0.25
eq statements | 0.4 | 0.4 | 0.03
jacobian | 5.7 | 5.7 | 0.11
autowrap | 7.2 | 37 | -
get_next_cmd mean | 0.017 | 0.00018 | 0.098
get_next_cmd std | 0.0003 | 0.000004 | 0.001

4. a controller that tries to create a certain pose of both hands relative to each other, which is what you have suggested yesterday:

\ | sympy + numpy | sympy + cython | symengine
---|---|---|---
init | 140 | 170 | 0.36
eq statements | 0.31 | 0.31 | 0.003
jacobian | 123 | 123 | 0.12
autowrap | 16 | 46 | -
get_next_command | 0.043 | 0.00012 | 0.23
get_next_cmd std | 0.0007 | 0.000004 | 0.0035

It should be noted that it takes 25s to compile the fk equations for the pr2 using cython and 0.9 using numpy. This is done every time even though it's unnecessary for the joint state controller.

As expected, symengine has no problem with differentiating huge equations. It also seems like cython's get_next_command call does not correlate with the function complexity at all.

Next I'm gonna work on adding tensorflow and theano to that list

**Comment by airballking** [comment]
@ichumuh Thanks a lot for this update! 

I have two questions. 

When you say "it takes ...0.9s... to compile the fk equations for the pr2 using ... numpy...", do you mean that if we just write out regular numpy expressions we get (1) runtime compilation at around 1 Hz, and (2) subsequent evaluation at around 20Hz?

Why is it not possible to combine symengine with numpy or cython?

**Comment by ichumuh** [comment]
Sorry, compile was not the correct word. I was referring to the autowrap step. It consists of two parts. (1) autowrap fk expressions (2) autowrap expressions that produce the matrices for the qp problem.

I need to evaluate the fk to set the default goal in all but the joint state controller. I also need it as the starting point for the line in the 3. controller. If we want to change the controller during runtime we can skip the (1) part. That would save 25s with cython for all subsequent controllers.
Additionally, we could probably compute and store this offline. Especially for cython this would save 25s in the autowrap step. 

It is possible to combine these two, but symengine does not have an autowrap function.
That means we have to translate it into a sympy expression and then call sympy.autowrap. My guess is that this step would take as much time as listed in the "eq statements" row.
Do you want me to try that out?

**Comment by isuruf** [comment]
symengine's lambdify has 2 backends. `lambda` and `llvm` which are comparable to sympy's `numpy` and `cython` methods.

**Comment by ichumuh** [comment]
Thanks for the info! I'm gonna try that out.

**Comment by airballking** [comment]
@isuruf Thanks for the tip! Which of the two backends is the default one? And, can you comment on which one is faster when generating expression vs. evaluating expressions?

Also, I am curious how you found out about our project. Are you also interested in robot control?

**Comment by ichumuh** [comment]
In sympy, the method that turns expressions into numpy functions is called lambdify but the one for cython is called autowrap. I just called everything autowrap because I thought it was less confusing. If I use symengines lambdify, which I currently don't, it should introduce the "autowrap" step but speed up the evaluation time.

**Comment by ichumuh** [comment]
@airballking I added symengine + lambda to the tables above. Like @isuruf said, it's comparable to numpy. lambdify takes less time but the resulting function seems to be slower. 
If I try to use llvm, symengine tells me that it's not compiled with llvm support. I guess I would have to compile it from sources.

**Comment by airballking** [comment]
@ichumuh thanks for the update of the tables regarding symengine + lambda.

Looking at symengine + lambda would indeed be interesting.

**Comment by ichumuh** [comment]
I have compiled symengine from sources with llvm support and updated the tables. It's almost as fast as cython but the autowrap step is also super fast. The lambda version is faster as well, seems like symengine from pip is outdated. 
However, with this installation my line constraint for the cart controller somehow produces infinities which causes the test to fail.
I'm gonna investigate some more.

**Comment by airballking** [comment]
Aha. Sounds promising! :)

**Comment by ichumuh** [comment]
I have found the problem with the line constraint, fixed it and added the number to the table. 
Looks pretty good to me. The only problem left is that we have to compile symengine from sources.
I think I don't have to try out theano and tensorflow anymore right?

**Comment by airballking** [comment]
@ichumuh So, you recommend going with symengine with LLVM as a backend? Looking at the worst cases from your table, that gives us 3s for compiling a new motion and 1250Hz of update frequency, correct. The former is a bit slow, while the latter is very nice. 

If these numbers turn out to be correct, I think we'll have to look into caching compiled expression. @ichumuh @amaldo @aroefer What do you think?

@ichumuh how much work is it to compile symengine + LLVM from source. Do you see a way of automating the process using the ROS infrastructure?

@ichumuh I'd be interesting in comparing with Theano? How much time would it take you to do the comparison?

**Comment by ichumuh** [comment]
symengine + LLVM outperforms everything else. So as long as we don't come up with anything better I think thats the way to go. I have just run the tests on my office pc (3.4 ghz 16gb ram). The worst case for the init was 4s and get_next_command 0.0012.

I think it should be relatively easy to automate this using the ros infrastructure because symengine uses cmake.

**Comment by airballking** [comment]
Compiling via CMake is indeed a good fit with ROS.

Given that you told me offline that you guess it would take 1-3 days to benchmark Theano, I think we should leave that for a later time and go with symengine + LLVM for now.

**Comment by isuruf** [comment]
> Also, I am curious how you found out about our project.
Just a random github search. 

> Are you also interested in robot control?
Nope

If you are not doing any broadcasting or have multiple outputs, following might be faster. (It avoids a few checks in python)
```
def f(**kwargs):
        filtered_args = [kwargs[k] for k in str_params]
        out = np.empty(function.shape)
        fast_f.unsafe_real(np.array(filtered_args, dtype=np.double), out)
        return  np.nan_to_num(out)
```
