### ISSUE TITLE
PyBullet(==3.0.8<3.1.2) Import Error

### ISSUE THREAD

**Issue by tlipps** [SemRoCo/giskardpy#74]
With the current installation script in the readme.md, testing and running giskardpy is not possible, due to of a pybullet import error. `sudo pip install pybullet` from the install script installs currently at least the version 3.1.2 on melodic. If the test code from the function `test_bowl_and_cup` is run, the following error log is produced:

```
ERROR: not found: /home/thomas/ros_ws/src/giskardpy/test/test_integration_pr2.py::TestCollisionAvoidanceGoals::test_bowl_and_cup
(no name '/home/thomas/ros_ws/src/giskardpy/test/test_integration_pr2.py::TestCollisionAvoidanceGoals::test_bowl_and_cup' in any of [<Module 'test/test_integration_pr2.py'>])

test/test_integration_pr2.py:None (test/test_integration_pr2.py)
ImportError while importing test module '/home/thomas/ros_ws/src/giskardpy/test/test_integration_pr2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
test_integration_pr2.py:22: in <module>
    from giskardpy.robot import Robot
../src/giskardpy/robot.py:12: in <module>
    from giskardpy.pybullet_world_object import PyBulletWorldObject
../src/giskardpy/pybullet_world_object.py:4: in <module>
    import giskardpy.pybullet_wrapper as pw
../src/giskardpy/pybullet_wrapper.py:6: in <module>
    import pybullet as p
E   ImportError: /home/thomas/.local/lib/python2.7/site-packages/pybullet.so: undefined symbol: PyUnicode_AsUTF8

```

The problem can be solved by using the pybullet version 3.0.8 (maybe later versions work too).

**Comment by ichumuh** [comment]
It works with python3/noetic. So it seems like they broke the python 2 support. I guess that is never going to get fixed. Especially because the don't allow issues on their github anymore. 
You can switch to 20.04+noetic if you want. Giskards devel works fine with it.

**Comment by ichumuh** [comment]
If you do, you should look at this issue: https://github.com/code-iai/iai_maps/issues/83#issue-782218694

**Comment by ichumuh** [comment]
updated readme e44d0dcf01b6fc3b57690556994d8796c91c134c
